/-
Copyright (c) 2025 Robin Carlier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Robin Carlier
-/
module

public import SymmMonCoherence.SList.Basic
public import SymmMonCoherence.CategoryWeight
public import SymmMonCoherence.SymmetricGroupCoxeterSystem
/-! # Characterizing morphisms in symmetric lists.

In this file, we characterize morphisms in the category `SList C` in the
following way: to each morphism `f : L ⟶ L'`, one can attach a formal permutation
`toPerm f : Equiv.Perm ℕ`, and two morphisms are equal if and only if the
attached formal permutations are equal.

The idea is simple: the relations that define symmetric lists are essentially in
one-to-one correspondence with the relations that present
the symmetric group as a Coxeter group; this is the argument one usually goes with
in pen-and-paper mathematics (see e.g [MacLane CWM]), but the formal realization of this argument
is in fact rather involved.

To define the formal permutation attached to a morphism, we first attach labels
(realized as `weight`) that live
in `FreeMonoid ℕ` to every (formal composition of) generating morphisms: the `swap` morphism
is labelled by `0`, and prepending an element to a morphism "shifts" the label by
one: e.g `a::b::(swap c d (e::nil)) : [a,b,c,d,e] ⟶ [a,b,d,c,e]` is labelled with `2`.
This way, a generating morphism is labelled with the first index of the list that
gets swapped. Formal compositions of generating morphisms (i.e., morphism in `FreeSListQuiv C`)
gets labels in `FreeMonoid ℕ` ("words") attached to them.

The relations between the morphisms make it so that two morphisms in relation will have
labels related by the relation defined by the Coxeter matrix Ainf. Hence morphisms in
`SList C` have a well-defined label in the monoid `Ainf.Monoid` (which is isomorphic to the
corresponding Coxeter group). As one can realize this monoid as a multiplicative subset of
`Equiv.Perm ℕ`, this defines the formal permutation of a morphism: by this definition, the
`swap` morphism gets sent to the permutation `Equiv.swap 0 1`, and
e.g., `a::b::(swap c d (e::nil)) : [a,b,c,d,e] ⟶ [a,b,d,c,e]` is labelled with `Equiv.swap 2 3`.
This definition realizes the idea that the "formal permutation" attached to a morphism is the
permutation of the indices of the source and target that this morphism performed.

The converse (that two morphisms with same formal permutations are equal) is harder:
one has to first work with formal compositions of generating morphisms
(i.e., morphisms in `FreeSListQuiv C`) and labels in free monoids and show that
1. Any two formal compositions of generating morphisms with same source, target and label are equal
2. Any two formal compositions of generating morphisms with same source and label have equal targets
3. For suitable labels and sources, one can find formal compositions of generating morphisms out
  of the given source with given label.
4. Using 1 and 2, that for each relation in the Coxeter matrix `Ainf`, one can find an
explicit morphisms whose label realizes these relations, and that these morphisms reduce to
identities in `SList`.
5. Using all of the points above and the definition of the equivalence relations generated by the
relations in Ainf and the equivalence relation generated by `CategoryTheory.Q₁.HomEquiv₀`,
show that any two paths are in relation if the corresponding labels in `Ainf.Monoid` are equal.

Point 4. is rather tedious as one needs to repeat essentially the same procedure for every morphism:
because of the inductive nature of generating morphisms:
one needs to decompose the source and target of the morphism, construct by hand a "candidate"
morphism with the right label, show that the original morphism is equal to the candidate
(since they have same label), and then show that the candidate morphism simplifies to an identity by
invoking the relations that define symmetric lists.

Point 5. hides the technicality from point 3. that labels need to be "suitable" in order to be
realized by explicit morphisms: by construction, paths of generating morphisms between lists
of length `n + 2` cannot have labels that are words involving natural numbers ≥ n, so in point 5,
two words may *a priori* be related because of transitivity through words that are "too big".
One has in fact to use that `Aₙ.Monoid` injects into `Ainf.Monoid`,
which essentially means that two words in `FreeMonoid ℕ` involving only letters coming from
`Fin (n + 1)` are in relation for the relation that defines `Ainf.Monoid` if and only if they are
for the relation that defines `Aₙ.Monoid`. This means that when generating the symmetric reflexive
closure of the base relation, one may assume that all extra words that appear (e.g for transitivity)
also only involve letters from `Fin (n + 1)`, which we are then able to realize as morphisms.

-/

@[expose] public section

attribute [-simp] CoxeterMatrix.toCoxeterSystem_simple
attribute [-simp] CategoryTheory.Paths.of_obj
attribute [-simp] CategoryTheory.Paths.of_map

universe u
namespace CategoryTheory.SList

variable {C : Type u}

namespace SListQuiv

/-- A base `ℕ`-valued label attached to a generating morphism. A swap morphism is valued
`0`, and prepending an element of `C` to a morphism adds 1 to the label.

Informally, this label records the "index" at which a variable swap occurs. -/
def labelling₀ : Quiver.Labelling (SListQuiv C) ℕ
  | _, _, .swap x y l => 0
  | _, _, .cons z f => labelling₀ f + 1

/-- A `Fin (n + 1)`-valued label attached to a generating morphism. A swap morphism is valued
`0`, and prepending an element of `C` to a morphism adds 1 to the label.

Informally, this label records the "index" at which a variable swap occurs.

This way of thinking about the label is only well-defined if the length of the input is
large enough, but it is convenient to have it defined without restriction on the length. -/
def finLabelling₀ (n : ℕ) : Quiver.Labelling (SListQuiv C) (Fin (n + 1)) := fun _ _ f =>
  Fin.ofNat (n + 1) (labelling₀ f)

/-- The labelling `labelling₀` as an element in `FreeGroup ℕ`. -/
def labelling₁ : Quiver.Labelling (SListQuiv C) (FreeGroup ℕ) := fun _ _ f =>
    FreeGroup.of <| labelling₀ f

/-- The labelling `labelling₀` as an element in `FreeMonoid ℕ`. -/
def labelling₁Mon : Quiver.Labelling (SListQuiv C) (FreeMonoid ℕ) := fun _ _ f =>
    FreeMonoid.of <| labelling₀ f

/-- The labelling `finLabelling₀` as an element in `FreeMonoid (Fin (n + 1))`. -/
def finLabelling₁Mon (n : ℕ) : Quiver.Labelling (SListQuiv C) (FreeMonoid (Fin (n + 1))) :=
  fun _ _ f => FreeMonoid.of <| finLabelling₀ n f

lemma labelling₁_eq {i j : SListQuiv C} (f : i ⟶ j) :
  labelling₁ f = FreeMonoid.toFreeGroup _ (labelling₁Mon f) := rfl

def labelling₂ : Quiver.Labelling (SListQuiv C) Ainf.Group := fun _ _ f =>
    Ainf.toCoxeterSystem.simple <| labelling₀ f

def labelling₂Mon : Quiver.Labelling (SListQuiv C) Ainf.Monoid := fun _ _ f =>
  Ainf.groupToMonoid (labelling₂ f)

def AₙLabelling (n : ℕ) : Quiver.Labelling (SListQuiv C) (CoxeterMatrix.Aₙ (n + 1)).Monoid :=
  fun _ _ f => PresentedMonoid.mk _ <| finLabelling₁Mon n f

lemma labelling₀_lt {i j : SListQuiv C} (f : i ⟶ j) : labelling₀ f + 1 < i.length := by
  induction f using SListQuiv.induction <;> grind [labelling₀]

lemma labelling₀_le {i j : SListQuiv C} (f : i ⟶ j) : labelling₀ f + 2 ≤ i.length := by
  induction f using SListQuiv.induction <;> grind [labelling₀]

lemma AₙLabelling_to_Ainf (n : ℕ) {i j : SListQuiv C} (f : i ⟶ j) (hn : n + 2 = i.length) :
    AnToAinfMonoid _ (AₙLabelling n f) = labelling₂Mon f := by
  induction f using SListQuiv.induction with
  | sw x y l =>
    dsimp [AₙLabelling, finLabelling₁Mon, finLabelling₀]
    suffices h : labelling₀ (.swap x y l) % (n + 1) = labelling₀ (.swap x y l) by
      rw [h]
      simp [labelling₀, labelling₂Mon, labelling₂, CoxeterMatrix.toCoxeterSystem_simple,
        CoxeterMatrix.groupToMonoid_simple]
    simp [labelling₀]
  | @cons x l l' f h =>
    dsimp [AₙLabelling, finLabelling₁Mon, finLabelling₀, labelling₀, labelling₂Mon, labelling₂]
    suffices h : (labelling₀ f + 1) % (n + 1) = labelling₀ f + 1 by
      rw [h]
      simp [CoxeterMatrix.toCoxeterSystem_simple]
    simp only [Nat.mod_succ_eq_iff_lt, Nat.succ_eq_add_one, add_lt_add_iff_right]
    have := labelling₀_le f
    grind

@[simp]
lemma labelling₁_swap (x y : C) (l : SListQuiv C) : labelling₁ (.swap x y l) = .of 0 := rfl

@[simp]
lemma labelling₂_swap (x y : C) (l : SListQuiv C) : labelling₂ (.swap x y l) =
    Ainf.toCoxeterSystem.simple 0 := rfl

namespace FreeSListQuiv

@[no_expose] def mkWeight {M : Type*} [Monoid M] (L : Quiver.Labelling (SListQuiv C) M) :
    weight (FreeSListQuiv C) M :=
  .mk (FreeSListQuiv.lift (fun _ ↦ .op <| .star M) (fun {_ _} f ↦ Quiver.Hom.op (L f)))

@[simp, grind =]
lemma mkWeight_app_ι {M : Type*} [Monoid M] {L : Quiver.Labelling (SListQuiv C) M}
    {x y : SListQuiv C} (f : x ⟶ y) :
    (mkWeight L).app ((FreeSListQuiv.ι C).map f) = L f := by
  simp [weight.app_mk, mkWeight]

set_option backward.isDefEq.respectTransparency false in
lemma mkWeight_app_swap {M : Type*} [Monoid M] {L : Quiver.Labelling (SListQuiv C) M}
    {x y : C} (l : FreeSListQuiv C) :
    (mkWeight L).app (FreeSListQuiv.swap x y l) = L (β₀_ x y (FreeSListQuiv.equiv l)) := by
  cases l
  simp only [← FreeSListQuiv.swap_eq, mkWeight_app_ι]
  rfl

end FreeSListQuiv

abbrev w₀ : weight (FreeSListQuiv C) (FreeMonoid ℕ) := FreeSListQuiv.mkWeight labelling₁Mon
abbrev w₁ : weight (FreeSListQuiv C) (FreeGroup ℕ) := FreeSListQuiv.mkWeight labelling₁
abbrev w₂ : weight (FreeSListQuiv C) Ainf.Group := FreeSListQuiv.mkWeight labelling₂
abbrev w₀Fin (n : ℕ) : weight (FreeSListQuiv C) (FreeMonoid (Fin (n + 1))) :=
  FreeSListQuiv.mkWeight (finLabelling₁Mon n)
abbrev wFin (n : ℕ) : weight (FreeSListQuiv C) (CoxeterMatrix.Aₙ (n + 1)).Monoid :=
  FreeSListQuiv.mkWeight (AₙLabelling n)

open scoped FreeSListQuiv

@[simp]
lemma w₀_swap (x y : C) (l : FreeSListQuiv C) : w₀.app (FreeSListQuiv.swap x y l) = .of 0 := by
  simp [FreeSListQuiv.mkWeight_app_swap, labelling₁Mon, labelling₀]

@[simp]
lemma w₂_swap (x y : C) (l : FreeSListQuiv C) :
    w₂.app (FreeSListQuiv.swap x y l) = Ainf.simple 0 := by
  simp only [FreeSListQuiv.mkWeight_app_swap, labelling₂_swap]
  rfl

@[simp]
lemma labelling₁_cons {i j : SListQuiv C} (f : i ⟶ j) (x : C) :
    labelling₁ (.cons x f) = shift' (labelling₁ f) :=
  rfl

lemma labelling₂_eq {i j : SListQuiv C} (f : i ⟶ j) :
    labelling₂ f = PresentedGroup.mk _ (labelling₁ f) :=
  rfl

set_option backward.isDefEq.respectTransparency false in
@[simp]
lemma w₁_app_consPath {i j : FreeSListQuiv C} (f : i ⟶ j) (x : C) :
    w₁.app (x ::_ₘ f) = shift' (w₁.app f) := by
  induction f using FreeSListQuiv.hom_induction with
  | id => simp
  | @comp u v p q r h =>
    simp [h, ← FreeSListQuiv.cons_map_def]

set_option backward.isDefEq.respectTransparency false in
lemma w₂_app_eq {i j : FreeSListQuiv C} (f : i ⟶ j) :
    w₂.app f = PresentedGroup.mk _ (w₁.app f) := by
  induction f using FreeSListQuiv.hom_induction with
  | id => simp
  | comp p q r =>
    simp only [weight.weight_comp, r, FreeSListQuiv.mkWeight_app_ι, map_mul, mul_right_inj]
    rfl

set_option backward.isDefEq.respectTransparency false in
lemma w₂_app_eq' {i j : FreeSListQuiv C} (f : i ⟶ j) :
    Ainf.groupToMonoid (w₂.app f) = PresentedMonoid.mk _ (w₀.app f) := by
  induction f using FreeSListQuiv.hom_induction with
  | id => simp
  | comp p q h =>
    simp only [weight.weight_comp, FreeSListQuiv.mkWeight_app_ι, labelling₂_eq,
      labelling₁_eq, map_mul, h]
    rfl

@[simp]
lemma labelling₂_cons {i j : SListQuiv C} (f : i ⟶ j) (x : C) :
    labelling₂ (.cons x f) = Ainf.shift 1 (labelling₂ f) :=
  rfl

set_option backward.isDefEq.respectTransparency false in
@[simp]
lemma w₂_app_consPath {i j : FreeSListQuiv C} (f : i ⟶ j) (x : C) :
    w₂.app (x ::_ₘ f) = Ainf.shift 1 (w₂.app f) := by
  induction f using FreeSListQuiv.hom_induction with
  | id => simp
  | @comp u v p q h r => simp [r, ← FreeSListQuiv.cons_map_def]

private lemma ainfToPerm_w₂_apply_lt_of_lt {L₁ L₂ : FreeSListQuiv C}
    (f : L₁ ⟶ L₂) (i : ℕ)
    (hi : i < L₂.toList.length) : (AinfToPerm (w₂.app f)) i < L₁.toList.length := by
  induction f using FreeSListQuiv.hom_induction generalizing i with
  | id => simpa using hi
  | @comp L₁ L₂ L₃ p q hp =>
    simp only [FreeSListQuiv.ι_toList, toList_length] at hp hi
    have hl₁₂ : L₁.length = L₂.length := FreeSListQuiv.length_eq_of_hom p
    have hl₂₃ : L₂.length = L₃.length := FreeSListQuiv.length_eq_of_hom ((FreeSListQuiv.ι _).map q)
    simp only [weight.weight_comp, FreeSListQuiv.mkWeight_app_ι, labelling₂, map_mul,
      AinfToPerm_simple, Equiv.Perm.coe_mul, Function.comp_apply, FreeSListQuiv.ι_toList,
      toList_length, gt_iff_lt]
    apply hp
    grind [labelling₀_lt q]

theorem _root_.List.getElem_of_eq' {α : Type*} {l : List α} {i i' : Nat} (h : i = i')
    (w : i < l.length) :
    l[i] = l[i']'(h ▸ w) := by cases h; rfl

private lemma getElem_toList_eq_perm_apply'
    {L₁ L₂ : SListQuiv C}
    (f : L₁.Hom L₂) (i : ℕ)
    (hi : i < L₂.toList.length) :
    (L₂.toList)[i] =
    (L₁.toList)[(AinfToPerm (w₂.app (FreeSListQuiv.ι C |>.map f))) i]'
      (ainfToPerm_w₂_apply_lt_of_lt (FreeSListQuiv.ι C |>.map f) _ hi) := by
  induction f generalizing i with grind [labelling₂, labelling₀, AinfToPerm_simple]

private lemma getElem_toList_eq_perm_apply {L₁ L₂ : FreeSListQuiv C} (f : L₁ ⟶ L₂)
    (i : ℕ) (hi : i < L₂.length) :
    (L₂.toList)[i] =
      (L₁.toList)[AinfToPerm (w₂.app f) i]'(ainfToPerm_w₂_apply_lt_of_lt f _ hi) := by
  induction f using FreeSListQuiv.hom_induction generalizing i with
  | id => simp
  | @comp l₁ l₂ l₃ p q hr =>
    simp only [toList_length, FreeSListQuiv.ι_length, FreeSListQuiv.ι_toList, weight.weight_comp,
      FreeSListQuiv.mkWeight_app_ι, map_mul, Equiv.Perm.coe_mul, Function.comp_apply] at hi ⊢ hr
    have := FreeSListQuiv.length_eq_of_hom p
    have := getElem_toList_eq_perm_apply' q
    simp only [toList_length, FreeSListQuiv.mkWeight_app_ι] at this
    rw [this i hi]
    have : (AinfToPerm (labelling₂ q)) i < l₂.length := by
      simpa using ainfToPerm_w₂_apply_lt_of_lt
        ((FreeSListQuiv.ι C).map q) i hi
    exact hr (AinfToPerm (labelling₂ q) i) this

set_option backward.isDefEq.respectTransparency false in
lemma wFin_app_eq' (n : ℕ) {i j : FreeSListQuiv C} (f : i ⟶ j) :
    (wFin n).app f = PresentedMonoid.mk _ ((w₀Fin n).app f) := by
  induction f using FreeSListQuiv.hom_induction with
  | id => simp
  | comp p q h => simp [h, finLabelling₁Mon, AₙLabelling]

lemma w₂_app_eq_of_homEquiv
    {i j : FreeSListQuiv C} (f g : i ⟶ j) (h : FreeSListQuiv.HomEquiv C f g) :
    w₂.app f = w₂.app g := by
  induction h with
  | swap_naturality X Y f =>
    simp only [weight.weight_comp, w₂_swap, w₂_app_consPath, FreeSListQuiv.mkWeight_app_ι]
    have e := Ainf.toCoxeterSystem.simple_mul_simple_pow 0 (labelling₀ f + 1 + 1)
    simp only [Ainf_M, Matrix.of_apply, Nat.right_eq_add, Nat.add_eq_zero_iff, OfNat.ofNat_ne_zero,
      and_false, ↓reduceIte, one_ne_zero, and_self, zero_add, or_self, pow_two,
      mul_eq_one_iff_inv_eq, mul_inv_rev, CoxeterSystem.inv_simple] at e
    simpa [labelling₂, CoxeterMatrix.toCoxeterSystem_simple] using e.symm
  | swap_swap X Y l => simp
  | triple X Y Z l =>
    simp only [weight.weight_comp, w₂_swap, w₂_app_consPath, Ainf.shift_simple 1, zero_add]
    have e := Ainf.toCoxeterSystem.simple_mul_simple_pow 0 1
    simp only [Ainf_M, Matrix.of_apply, zero_ne_one, ↓reduceIte, Nat.reduceAdd,
      OfNat.ofNat_ne_zero, zero_add, or_true, pow_three, mul_eq_one_iff_inv_eq, mul_inv_rev,
      CoxeterSystem.inv_simple] at e
    have := congr($e * Ainf.toCoxeterSystem.simple 1)
    simpa [← mul_assoc] using this.symm
  | cons X f f' h₀ hrec => grind [w₂_app_consPath]

lemma w₂_app_eq_of_compClosure_homEquiv {i j : FreeSListQuiv C} (f g : i ⟶ j)
    (h : (HomRel.CompClosure (FreeSListQuiv.HomEquiv C)) f g) :
    w₂.app f = w₂.app g := by
  cases h with | intro i j f m₁ m₂ g h =>
  simpa using w₂_app_eq_of_homEquiv m₁ m₂ h

end SListQuiv

public section toAinf
open SListQuiv

def toAinf : weight (SList C) Ainf.Group :=
  .mk <| SList.lift w₂.F <| by
    intro x y f g h
    apply Quiver.Hom.unop_inj
    simp_rw [weight.app_eq]
    exact w₂_app_eq_of_homEquiv _ _ h

@[simp, grind =]
lemma toAinf_π {l l' : FreeSListQuiv C} (f : l ⟶ l') :
    toAinf.app ((π C).map f) = w₂.app f := by
  simp only [toAinf, weight.app_mk]
  generalize_proofs h
  simp [lift_π_obj (h := h), lift_π_map (h := h), weight.app_eq]

@[simp, grind =]
lemma toAinf_swap (x y : C) (l : SList C) :
    toAinf.app (β~ x y l) = Ainf.simple 0 := by
  simp only [toAinf, weight.app_mk]
  rfl

@[simp, grind =]
lemma toAinf_cons (x : C) {l l' : SList C} (f : l ⟶ l') :
    toAinf.app ((x>~).map f) = Ainf.shift 1 (toAinf.app f) := by
  simp only [toAinf, weight.app_mk]
  induction f with | @h u v f =>
  generalize_proofs h
  change ((lift w₂.F h).map (π C |>.map <| x ::_ₘ f)).unop = _
  simp [weight.app_eq, SList.lift_π_obj (h := h), SList.lift_π_map (h := h)]

end toAinf

public section toPerm
open SListQuiv

def toPerm : weight (SList C) (Equiv.Perm ℕ) :=
  toAinf.postComp AinfToPerm

@[simp, grind =]
lemma toPerm_swap (x y : C) (l : SList C) :
    toPerm.app (β~ x y l) = Equiv.swap 0 1 := by
  simp [toPerm]

@[simp, grind =]
lemma toPerm_app_cons_apply_zero (x : C) {l l' : SList C} (f : l ⟶ l') :
    toPerm.app ((x>~).map f) 0 = 0 := by
  simp only [toPerm, weight.postComp_app, toAinf_cons]
  generalize toAinf.app f = u
  induction u using Ainf.toCoxeterSystem.simple_induction with
  | simple i => simp only [Ainf.shift_simple' 1, AinfToPerm_simple]; grind
  | one => simp
  | mul w w' h₀ h₀' => simp [h₀, h₀']

@[simp, grind =]
lemma toPerm_app_cons_apply_succ (x : C) {l l' : SList C} (f : l ⟶ l') (k : ℕ) :
    toPerm.app ((x>~).map f) (k + 1) = (toPerm.app f) k + 1 := by
  simp only [toPerm, weight.postComp_app, toAinf_cons]
  generalize toAinf.app f = u
  induction u using Ainf.toCoxeterSystem.simple_induction generalizing k with
  | simple i => simp only [Ainf.shift_simple' 1, AinfToPerm_simple]; grind
  | one => simp
  | mul w w' h₀ h₀' => simp [h₀, h₀']

theorem toPerm_app_eq_of_lt {x y : SList C} (f : x ⟶ y) (k : ℕ) (hk : y.length ≤ k) :
    (toPerm.app f) k = k := by
  simp only [toPerm, weight.postComp_app]
  induction f using SList.hom_induction with | h f =>
  induction f using FreeSListQuiv.hom_induction with
  | id => simp
  | comp p q hq =>
    have := SListQuiv.length_eq_of_hom q
    simp only [Functor.map_comp, weight.weight_comp, toAinf_π, FreeSListQuiv.mkWeight_app_ι,
      labelling₂, map_mul, AinfToPerm_simple, Equiv.Perm.coe_mul, Function.comp_apply]
    have := labelling₀_lt q
    grind

@[grind .]
theorem toPerm_app_lt_of_lt {L₁ L₂ : SList C} (f : L₁ ⟶ L₂) (k : ℕ) (hk : k < L₂.length) :
    (toPerm.app f) k < L₁.length := by
  by_contra!
  have := toPerm_app_eq_of_lt (inv f) (toPerm.app f k) this
  simp only [weight.app_inv, Equiv.Perm.coe_inv, Equiv.symm_apply_apply] at this
  grind [SList.length_eq_of_hom f]

theorem getElem_toList_toPerm {L₁ L₂ : SList C} (f : L₁ ⟶ L₂) (i : ℕ) (hi : i < L₂.length) :
    L₂.toList[i] = L₁.toList[toPerm.app f i]'(toPerm_app_lt_of_lt f i hi) := by
  cases f with | @h x y f =>
  simp only [π_obj_toList, toPerm, weight.postComp_app, toAinf_π]
  exact getElem_toList_eq_perm_apply f _ _

end toPerm

namespace SListQuiv

lemma eq_of_labelling₀_eq {i j : (SListQuiv C)} {f g : i ⟶ j}
    (h : labelling₀ f = labelling₀ g) :
    f = g := by
  induction f using SListQuiv.induction with
  | sw x y l =>
    cases g using SListQuiv.induction with
    | sw x y l => rfl
    | cons z g => simp [labelling₀] at h
  | cons z f hr =>
    cases g using SListQuiv.induction with
    | sw x y l => simp [labelling₀] at h
    | cons z f =>
      simp only [labelling₀, Nat.add_right_cancel_iff] at h
      obtain rfl := hr h
      rfl

lemma eq_of_labelling₀_eq' {i j k : SListQuiv C} {f : i ⟶ j} {g : i ⟶ k}
    (h : labelling₀ f = labelling₀ g) :
    j = k := by
  induction f using SListQuiv.induction generalizing k with
  | sw x y l => cases g using SListQuiv.induction with
    | cons z _ => simp [labelling₀] at h
    | sw x y l => rfl
  | cons z f hr => cases g using SListQuiv.induction with
    | sw x y l => simp [labelling₀] at h
    | cons z _ =>
      simp only [labelling₀, Nat.add_right_cancel_iff] at h
      obtain rfl := hr h
      rfl

lemma eq_of_labelling₀_eq'' {i j k : SListQuiv C} {f : i ⟶ j} {g : k ⟶ j}
    (h : labelling₀ f = labelling₀ g) :
    i = k := by
  induction f using SListQuiv.induction generalizing k with
  | sw x y l => cases g using SListQuiv.induction with
    | cons z _ => simp [labelling₀] at h
    | sw x y l => rfl
  | cons z f hr => cases g using SListQuiv.induction with
    | sw x y l => simp [labelling₀] at h
    | cons z _ =>
      simp only [labelling₀, Nat.add_right_cancel_iff] at h
      obtain rfl := hr h
      rfl

lemma _root_.FreeMonoid.mul_eq_of_eq_mul_of {α : Type*} {u v : FreeMonoid α} {a a' : α}
    (h : u * (.of a) = v * (.of a')) : u = v ∧ a = a' := by
  suffices h : a = a' by
    subst h
    simpa using h
  have toList_eq := congr(FreeMonoid.toList $h)
  have length_eq := congr(List.length $toList_eq)
  simp only [FreeMonoid.toList_mul, FreeMonoid.toList_of, List.length_append,
    List.length_cons, List.length_nil, zero_add, Nat.add_right_cancel_iff] at toList_eq length_eq
  simpa [length_eq] using congr(List.drop (FreeMonoid.toList u).length $toList_eq)

lemma eq_of_w₀_app_eq {i j : FreeSListQuiv C} {f g : i ⟶ j} (h : w₀.app f = w₀.app g) :
    f = g := by
  induction f using FreeSListQuiv.hom_induction with
  | id => cases g using FreeSListQuiv.hom_induction with
    | @comp i j k p q h' =>
      have := congr(FreeMonoid.length $h)
      simp [labelling₁Mon] at this
    | id => rfl
  | @comp u v w p q h' =>
    cases g using FreeSListQuiv.hom_induction with
    | id =>
      have := congr(FreeMonoid.length $h)
      simp [labelling₁Mon] at this
    | @comp u' v' w' p' q' h'' =>
      simp only [weight.weight_comp, FreeSListQuiv.mkWeight_app_ι, labelling₁Mon] at h
      have : labelling₀ q = labelling₀ q' := (FreeMonoid.mul_eq_of_eq_mul_of h).2
      obtain rfl : v = v' := eq_of_labelling₀_eq'' this
      obtain rfl : q = q' := eq_of_labelling₀_eq this
      simp only [mul_left_inj] at h
      obtain rfl := h' h
      rfl

@[simp]
lemma w₂_app_eq'' (n : ℕ) {i j : FreeSListQuiv C} (f : i ⟶ j) (hn : n + 2 = i.length) :
    AnToAinfMonoid _ ((wFin n).app f) = Ainf.groupToMonoid (w₂.app f) := by
  induction f using FreeSListQuiv.hom_induction with
  | id => simp [w₂]
  | @comp u v p q h r =>
    have := AₙLabelling_to_Ainf n h <| by
      have := FreeSListQuiv.length_eq_of_hom q
      grind
    simp [this, labelling₂Mon, r hn]

lemma eq_of_w₀_app_eq' {i j k : FreeSListQuiv C} {f : i ⟶ j} {g : i ⟶ k}
    (h : w₀.app f = w₀.app g) :
    j = k := by
  induction f using FreeSListQuiv.hom_induction generalizing k with
  | id =>
    cases g using FreeSListQuiv.hom_induction with
    | id => rfl
    | comp p q _ =>
      symm at h
      simp [labelling₁Mon] at h
  | @comp u v w p q r => cases g using FreeSListQuiv.hom_induction with
    | id => simp [labelling₁Mon] at h
    | @comp u' v' w' p' q' r' =>
      simp only [weight.weight_comp, FreeSListQuiv.mkWeight_app_ι, labelling₁Mon,
        forall_const] at h r r'
      have := FreeMonoid.mul_eq_of_eq_mul_of h
      grind [eq_of_labelling₀_eq', eq_of_labelling₀_eq]

lemma eq_of_w₀_eq'' {i j k : FreeSListQuiv C} {f : i ⟶ k} {g : j ⟶ k}
    (h : w₀.app f = w₀.app g) :
    i = j := by
  induction f using FreeSListQuiv.hom_induction generalizing j with
  | id =>
    cases g using FreeSListQuiv.hom_induction with
    | id => rfl
    | comp p q _ =>
      symm at h
      simp [labelling₁Mon] at h
  | @comp u v w p q r => cases g using FreeSListQuiv.hom_induction with
    | id => simp [labelling₁Mon] at h
    | @comp u' v' w' p' q' r' =>
      simp only [weight.weight_comp, FreeSListQuiv.mkWeight_app_ι, labelling₁Mon,
        forall_const] at h r r'
      have := FreeMonoid.mul_eq_of_eq_mul_of h
      obtain rfl : v = v' := eq_of_labelling₀_eq'' this.2
      grind [eq_of_labelling₀_eq', eq_of_labelling₀_eq]

abbrev valEmb (n : ℕ) : FreeMonoid (Fin n) →* FreeMonoid ℕ := FreeMonoid.lift (fun x ↦ .of x.val)

set_option backward.isDefEq.respectTransparency false in
lemma w₀Fin_consPath_map (n : ℕ) {i j : FreeSListQuiv C} (f : i ⟶ j) (x : C)
      (hn : i.length <= n + 2) :
    (w₀Fin (n + 1)).app (x ::_ₘ f) = succMon _ (w₀Fin n |>.app f) := by
  induction f using FreeSListQuiv.hom_induction with
  | id => simp
  | @comp u v w p q r =>
      simp only [Functor.map_comp, ← FreeSListQuiv.cons_map_def, weight.weight_comp, r hn,
        FreeSListQuiv.mkWeight_app_ι, finLabelling₁Mon, finLabelling₀, labelling₀,
        Fin.ofNat_eq_cast, map_mul, FreeMonoid.lift_eval_of, mul_right_inj]
      congr
      ext
      simp only [Fin.val_natCast, Fin.val_succ]
      rw [Nat.mod_eq_of_lt, Nat.mod_eq_of_lt] <;>
      · have := labelling₀_lt q
        simp at hn
        have l₁ : u.length = v.length := FreeSListQuiv.length_eq_of_hom p
        rw [← l₁] at this
        grind

set_option backward.isDefEq.respectTransparency false in
lemma w₀_consPath_map {i j : FreeSListQuiv C} (f : i ⟶ j) (x : C) :
    w₀.app (x ::_ₘ f) = shift'Mon 1 (w₀.app f) := by
  induction f using FreeSListQuiv.hom_induction with
  | id => simp
  | @comp u v w p q r => simpa [← FreeSListQuiv.cons_map_def, labelling₁Mon, labelling₀] using r

lemma w₀_prependPath_map (l : FreeSListQuiv C) {i j : FreeSListQuiv C} (f : i ⟶ j) :
    w₀.app (l ++ₘ f) = shift'Mon l.length (w₀.app f) := by
  cases l with | h l =>
  induction l with
  | nil =>
    induction f using FreeSListQuiv.hom_induction with
    | id => simp
    | @comp u v w p q r =>
      simp [labelling₁Mon, FreeSListQuiv.append_nil_map]
  | cons z l' r' =>
    induction f using FreeSListQuiv.hom_induction with
    | id => simp
    | @comp u v w p q r =>
      simp only [toList_length, FreeSListQuiv.ι_length, length_cons, Functor.map_comp,
        weight.weight_comp, FreeSListQuiv.mkWeight_app_ι, map_mul] at r r'
      simp [FreeSListQuiv.cons_obj_eq, FreeSListQuiv.append_cons_map, w₀_consPath_map,
        ← map_mul, r', shift'Mon_self]

lemma valEmb_w₀Fin {i j : FreeSListQuiv C} (f : i ⟶ j) (n : ℕ)
    (hn : i.length = n + 2) :
    valEmb _ (w₀Fin n |>.app f) = w₀.app f := by
  induction f using FreeSListQuiv.hom_induction with
  | id => simp
  | @comp u v w p q r =>
    have := labelling₀_lt q;
    have l₁ : u.length = v.length := FreeSListQuiv.length_eq_of_hom p
    have := r hn
    simp [finLabelling₁Mon, finLabelling₀, r hn, labelling₁Mon,
      Nat.mod_eq_of_lt (a := labelling₀ q) (b := n + 1) (by grind [Paths.of_obj])]

lemma eq_of_w₀Fin_eq {i j : FreeSListQuiv C} {f g : i ⟶ j} (n : ℕ)
    (hn : i.length = n + 2) (h : (w₀Fin n).app f = (w₀Fin n).app g) :
    f = g := by
  apply eq_of_w₀_app_eq
  induction f using FreeSListQuiv.hom_induction generalizing n with
  | id => cases g using FreeSListQuiv.hom_induction with
    | id => simp
    | comp p q _ => symm at h; simp [finLabelling₁Mon] at h
  | @comp u v w p q hr => cases g using FreeSListQuiv.hom_induction with
    | id => simp [finLabelling₁Mon] at h
    | @comp u' v' w p' q' r' =>
      simp only [toList_length, FreeSListQuiv.ι_length, weight.weight_comp,
        FreeSListQuiv.mkWeight_app_ι, finLabelling₁Mon, forall_const] at hr h r'
      have := FreeMonoid.mul_eq_of_eq_mul_of h
      have l_e := FreeSListQuiv.length_eq_of_hom p'
      have l_e' := FreeSListQuiv.length_eq_of_hom p
      simp only [toList_length, FreeSListQuiv.ι_length] at l_e l_e' hn p
      simp only [finLabelling₀, Fin.ofNat_eq_cast, Fin.ext_iff, Fin.val_natCast] at this
      have e : w₀.app p = w₀.app p' := by
        have := congr(valEmb _ $(this.1))
        rwa [valEmb_w₀Fin, valEmb_w₀Fin] at this <;> grind
      simp only [weight.weight_comp, e, FreeSListQuiv.mkWeight_app_ι, labelling₁Mon, mul_right_inj]
      congr 1
      rw [Nat.mod_eq_of_lt, Nat.mod_eq_of_lt] at this
      · grind
      · have := labelling₀_lt q'
        grind
      · have := labelling₀_lt q
        simp
        grind

lemma eq_of_w₀Fin_eq' {i j k : FreeSListQuiv C} {f : i ⟶ j} {g : i ⟶ k} (n : ℕ)
    (hn : i.length = n + 2) (h : (w₀Fin n).app f = (w₀Fin n).app g) :
    j = k := by
  apply eq_of_w₀_app_eq' (f := f) (g := g)
  induction f using FreeSListQuiv.hom_induction generalizing n with
  | id => cases g using FreeSListQuiv.hom_induction with
    | id => simp
    | comp p q _ => symm at h; simp [finLabelling₁Mon] at h
  | @comp u v w p q hr => cases g using FreeSListQuiv.hom_induction with
    | id => simp [finLabelling₁Mon] at h
    | @comp u' v' w p' q' r' =>
      simp only [toList_length, FreeSListQuiv.ι_length, weight.weight_comp,
        FreeSListQuiv.mkWeight_app_ι, finLabelling₁Mon, forall_const] at hr h r'
      have := FreeMonoid.mul_eq_of_eq_mul_of h
      have l_e := FreeSListQuiv.length_eq_of_hom p'
      have l_e' := FreeSListQuiv.length_eq_of_hom p
      simp only [toList_length, FreeSListQuiv.ι_length, finLabelling₀, Fin.ofNat_eq_cast,
        Fin.ext_iff, Fin.val_natCast, weight.weight_comp,
        FreeSListQuiv.mkWeight_app_ι] at l_e l_e' p this hn ⊢
      have e : w₀.app p = w₀.app p' := by
        have := congr(valEmb _ $(this.1))
        rwa [valEmb_w₀Fin, valEmb_w₀Fin] at this <;> grind
      simp only [e, labelling₁Mon, mul_right_inj]
      congr 1
      rw [Nat.mod_eq_of_lt, Nat.mod_eq_of_lt] at this
      · grind
      · have := labelling₀_lt q'
        grind
      · have := labelling₀_lt q
        grind

private lemma _root_.List.eq_cons_cons_of_length_eq_add_two {n : ℕ}
    (l : List C) (h : l.length = n + 2) : ∃ (a b : C) (l' : List C), l = a::b::l' := by
  induction l using List.twoStepInduction <;> grind

set_option backward.isDefEq.respectTransparency false in
lemma exists_hom_of_weight_eq (i : FreeSListQuiv C) (n : ℕ) (hj : i.length = n + 2)
    (w : FreeMonoid (Fin (n + 1))) :
    ∃ j : FreeSListQuiv C, ∃ f : i ⟶ j, (w₀Fin n).app f = w := by
  induction w generalizing i with
  | one =>
    use i, (𝟙 _)
    simp
  | of x =>
    cases i with |_ i
    induction i generalizing n with
    | nil => grind
    | cons a l r =>
      simp only [toList_length, FreeSListQuiv.ι_length, length_cons, Nat.add_right_cancel_iff] at hj
      cases x using Fin.cases with
      | zero =>
        cases l with
        | nil => grind
        | cons b l =>
          use (FreeSListQuiv.ι C |>.obj ( b ::… a ::… l)),
            (FreeSListQuiv.ι C |>.map <| .swap a b l)
          simp only [FreeSListQuiv.mkWeight_app_ι]
          rfl
      | succ i =>
        cases n with
        | zero => exact i.elim0
        | succ n =>
          obtain ⟨j₀, f₀, hj₀⟩ := r n i hj
          use (a ::_ j₀), (a ::_ₘ f₀)
          simp [w₀Fin_consPath_map n f₀ a (by grind), hj₀]
  | mul x y hx hy =>
    obtain ⟨j₀, f₀, rfl⟩ := hx i hj
    obtain ⟨j₁, f₁, rfl⟩ := hy j₀ (FreeSListQuiv.length_eq_of_hom f₀ ▸ hj)
    use j₁, f₀ ≫ f₁
    simp

set_option backward.isDefEq.respectTransparency false in
private lemma exists_cons_eq_of_weight_eq_shift_quiv
    {w : FreeMonoid ℕ} {i j : SListQuiv C}
    {f : i ⟶ j}
    (h : w₀.app (FreeSListQuiv.ι C |>.map f) = shift'Mon 1 w) (hij : 1 ≤ i.length) :
    ∃ x : C, ∃ i' j' : SListQuiv C, ∃ (f' : i' ⟶ j'),
    ∃ hi : (x ::… i') = i, ∃ hj : (x ::… j') = j,
    (FreeSListQuiv.ι C |>.map f) =
    eqToHom (by rw [← hi]; rfl) ≫
      (FreeSListQuiv.cons x |>.map (FreeSListQuiv.ι C |>.map f')) ≫
      eqToHom (by rw [← hj]; rfl) := by
  cases f using SListQuiv.induction with
  | sw x y l =>
    simp only [FreeSListQuiv.mkWeight_app_ι, ← FreeSListQuiv.cons_map_def, cons.injEq] at h ⊢
    cases w with
    | h0 => simp [labelling₁Mon] at h
    | ih x xs =>
      simp only [labelling₁Mon, labelling₀, map_mul, FreeMonoid.lift_eval_of] at h
      have := congr(FreeMonoid.length $h)
      simp only [FreeMonoid.length_of, FreeMonoid.length_mul, Nat.left_eq_add,
        FreeMonoid.length_eq_zero] at this
      simp only [this, mul_one] at h
      have := FreeMonoid.of_injective h
      simp at this
  | @cons x i j f =>
    use x, i, j, f, rfl, rfl
    simp [← FreeSListQuiv.cons_map_def]

lemma exists_cons_eq_of_weight_eq_shift
    {w : FreeMonoid ℕ} {i j : FreeSListQuiv C}
    {f : i ⟶ j}
    (h : w₀.app f = shift'Mon 1 w) (hij : 1 ≤ i.length) :
    ∃ x : C, ∃ i' j' : FreeSListQuiv C, ∃ (f' : i' ⟶ j'),
    ∃ hi : (x ::_ i') = i, ∃ hj : (x ::_ j') = j,
    f = eqToHom hi.symm ≫ (x ::_ₘ f') ≫ eqToHom hj := by
  induction f using FreeSListQuiv.hom_induction generalizing w with
  | @id i' =>
      simp only [toList_length, FreeSListQuiv.ι_length] at hij
      obtain ⟨k, t⟩ := Nat.exists_eq_add_of_le hij
      cases i' with | nil => grind | cons x i₀ =>
      use x, i₀, i₀, 𝟙 _
      simp [← FreeSListQuiv.cons_obj_eq]
  | @comp i' j' k' p q hr =>
      have u := w.reverse_reverse
      rw [← u] at h
      generalize w.reverse = w' at h
      cases w' with
      | h0 =>
        have : FreeMonoid.reverse (α := ℕ) 1 = 1 := rfl
        simp [this, labelling₁Mon] at h
      | ih x xs =>
        simp only [weight.weight_comp, FreeSListQuiv.mkWeight_app_ι, FreeMonoid.reverse_mul,
          FreeMonoid.reverse_of, map_mul] at h
        -- simp only [Paths.of_obj, Paths.of_map, w₀_comp, w₀_paths_of',
        --   FreeMonoid.reverse_mul, FreeMonoid.reverse_of, map_mul, FreeMonoid.lift_eval_of] at h
        dsimp [labelling₁Mon] at h
        have := FreeSListQuiv.length_eq_of_hom p
        simp only [toList_length, FreeSListQuiv.ι_length] at this hij
        obtain ⟨h₁, h₂⟩ := FreeMonoid.mul_eq_of_eq_mul_of h
        obtain ⟨x₀, i₀, j₀, f₀, hi₀, hj₀, hf₀⟩ := hr h₁ hij
        obtain ⟨x₁, i₁, j₁, f₁, hi₁, hj₁, hf₁⟩ :=
          exists_cons_eq_of_weight_eq_shift_quiv (f := q) (w := .of x)
            (by simpa [labelling₁Mon] using congr(FreeMonoid.of $h₂)) (by grind)
        obtain rfl : x₀ = x₁ := by
          rw [← hi₁, FreeSListQuiv.cons_obj_eq] at hj₀
          have := congr(FreeSListQuiv.toList $hj₀)
          grind [FreeSListQuiv.cons_toList, FreeSListQuiv.ι_toList]
        obtain rfl : j₀ = i₁ := by
          rw [← hi₁, FreeSListQuiv.cons_obj_eq] at hj₀
          have := congr(FreeSListQuiv.toList $hj₀)
          apply FreeSListQuiv.injective_toList
          grind
        use x₀, i₀, j₁, f₀ ≫ (FreeSListQuiv.ι C |>.map f₁), hi₀,
          congr(FreeSListQuiv.ι C |>.obj $hj₁)
        rw [hf₀, hf₁]
        simp

set_option backward.isDefEq.respectTransparency false in
/-- This is the first main "ugly lemma" where we check by hand that the relations implies that
morphisms have consistent targets -/
lemma eq_of_w₀Fin_monoidRelations {L₁ L₂ L₃ : FreeSListQuiv C}
    {f : L₁ ⟶ L₂} {g : L₁ ⟶ L₃} (n : ℕ)
    (hn : L₁.length = n + 2)
    (h : (CoxeterMatrix.Aₙ <| n + 1).monoidRelations (w₀Fin n |>.app f) (w₀Fin n |>.app g)) :
    L₂ = L₃ := by
  generalize hv : (w₀Fin n).app f = v at h
  generalize hw : (w₀Fin n).app g = w at h
  cases h with | intro i' j' =>
  obtain rfl : L₃ = L₁ := by
    have := FreeSListQuiv.length_eq_of_hom f
    have := FreeSListQuiv.length_eq_of_hom g
    apply eq_of_w₀Fin_eq' n (g := 𝟙 L₁) (f := g) (by grind)
    simpa
  clear hw g
  cases L₂ with | h L₂ =>
  cases L₃ with | h L₃ =>
  apply FreeSListQuiv.injective_toList
  apply List.ext_getElem (FreeSListQuiv.length_eq_of_hom f).symm
  intro i hi hi'
  simp_rw [FreeSListQuiv.equiv_ι_obj]
  have := getElem_toList_eq_perm_apply (f := f) i
    (by grind [FreeSListQuiv.equiv_ι_obj])
  simp only [FreeSListQuiv.ι_toList] at this
  rw [this]
  suffices w₂.app f = 1 by simp [this]
  have := w₂_app_eq' f
  replace hv := congr(valEmb _ $hv)
  simp only [valEmb_w₀Fin _ _ hn] at hv
  rw [hv] at this
  simp only [map_pow, map_mul, FreeMonoid.lift_eval_of, PresentedMonoid.mk_of,
    ← Ainf.groupToMonoid_simple] at this
  rw [← map_mul (f := Ainf.groupToMonoid), ← map_pow (f := Ainf.groupToMonoid),
    ← CoxeterMatrix.toCoxeterSystem_simple, Aₙ_m_eq,
    Ainf.toCoxeterSystem.simple_mul_simple_pow] at this
  have : Function.Injective Ainf.groupToMonoid := Ainf.monoidToGroupMulEquiv.toEquiv.symm.injective
  grind

lemma eq_of_w₀Fin_congen_rel {i j k : FreeSListQuiv C} {f : i ⟶ j} {g : i ⟶ k} (n : ℕ)
    (hn : i.length = n + 2)
    (h : ConGen.Rel (CoxeterMatrix.Aₙ (n + 1)).monoidRelations
      (w₀Fin n |>.app f) (w₀Fin n |>.app g)) :
    j = k := by
  generalize hv : (w₀Fin n).app f = v at h
  generalize hw : (w₀Fin n).app g = w at h
  induction h generalizing i j k f g with
  | of x y r =>
    subst hv
    subst hw
    exact eq_of_w₀Fin_monoidRelations n hn r
  | refl x => exact eq_of_w₀Fin_eq' n hn (hw ▸ hv)
  | symm r hr => exact hr hn hw hv|>.symm
  | @trans u v w r r' hr hr' =>
    obtain ⟨j', f', hf'⟩ := exists_hom_of_weight_eq i n hn v
    obtain rfl := hr hn hv hf'
    have := FreeSListQuiv.length_eq_of_hom f
    exact hr' (by grind) hf' hw
  | @mul u₁ u₂ v₁ v₂ r₁ r₂ hr₁ hr₂ =>
    obtain ⟨k₁, f₁, hf₁⟩ := exists_hom_of_weight_eq i n hn u₁
    obtain ⟨j₁, g₁, hg₁⟩ := exists_hom_of_weight_eq k₁ n
      (by have := FreeSListQuiv.length_eq_of_hom f₁; grind) v₁
    obtain ⟨k₂, f₂, hf₂⟩ := exists_hom_of_weight_eq i n hn u₂
    obtain ⟨j₂, g₂, hg₂⟩ := exists_hom_of_weight_eq k₂ n
      (by have := FreeSListQuiv.length_eq_of_hom f₂; grind) v₂
    obtain rfl : j = j₁ := eq_of_w₀Fin_eq' (f := f) (g := f₁ ≫ g₁) n hn (by grind)
    obtain rfl : k = j₂ := eq_of_w₀Fin_eq' (f := g) (g := f₂ ≫ g₂) n hn (by grind)
    obtain rfl := hr₁ hn hf₁ hf₂
    exact hr₂ (by have := FreeSListQuiv.length_eq_of_hom f₁; grind) hg₁ hg₂

end SListQuiv

section Relations

/-! The following section deals with the proof of the fact that given an endomorphism `f : L ⟶ L` in
`FreeSListQuiv C` whose label corresponds to a relation in `Ainf.Monoid`, i.e., whose label is one
of
- `«i» * «i»`
- `«i» * «i + 1» * «i» * «i + 1» * «i» * «i + 1»`
- `«i + 1» * «i» * «i + 1» * «i» * «i + 1» * «i»`
- `«i» * «j» * «i» * «j»` for `|j - i| ≥ 2`

then the corresponding endomorphism in `SList` is the identity. This is the "base case" to show
that paths with equal labels give equal morphisms in `SList`.

The proofs are a bit repetitive and all follow the same pattern:
since morphisms in `FreeSListQuiv C` have constrained sources and target,
one must first "decompose" L in a way that will make naming explicit morphisms out of `L` possible,
then one introduces a "candidate" morphism that realizes almost tautologically the given label, this
candidate must then be equal to `f` because it has the same label (and source/target).
Finally one checks that the candidate morphism indeed simplifies to an identity morphism in `SList`
by invoking the relevant relation in `SList` as each one of the four cases above correspond almost
directly to some relations that defines `SList` as a quotient of `FreeSListQuiv C`. -/

open SListQuiv

private theorem map_eq_of_label_eq_sq (k : ℕ) {L : FreeSListQuiv C}
    (hk : L.length = k + 2)
    (i : ℕ) (hi : i < k + 1)
    (f : L ⟶ L) (hwf : w₀.app f = FreeMonoid.of i * FreeMonoid.of i) :
    (π C).map f = (π C).map (𝟙 L) := by
  -- Setting up some names to make things shorter later on
  let gi₁ : C := (L.toList)[i]'(by grind)
  let gi₂ : C := (L.toList)[i + 1]'(by grind)
  let R := FreeSListQuiv.ι _ |>.obj <| asSListQuiv <| List.drop (i + 2) L.toList
  let P := FreeSListQuiv.ι _ |>.obj <| asSListQuiv <| List.take i L.toList
  -- breaking down `L`
  have :
    L = (P>>).obj (gi₁ ::_ (gi₂ ::_ R)) := by
    apply FreeSListQuiv.injective_toList
    simp [gi₁, gi₂, P, R]
  let g := eqToHom this.symm ≫ f ≫ eqToHom this
  suffices (π C).map g = (π C).map (𝟙 _) by
    simp only [Functor.map_comp, eqToHom_map, Functor.map_id, g] at this
    rw [eqToHom_comp_iff, comp_eqToHom_iff] at this
    simpa using this
  -- building a candidate morphism with the right label
  let u₀ := FreeSListQuiv.swap gi₁ gi₂ R
  let u₁ := FreeSListQuiv.swap gi₂ gi₁ R
  let f₀ := u₀ ≫ u₁
  -- The candidate morphism is equal to `g` because it has the right label
  have g_eq :
      g = ((FreeSListQuiv.ι _ |>.obj <|
        asSListQuiv <| List.take i L.toList)) ++ₘ f₀ := by
    apply eq_of_w₀_app_eq
    have : w₀.app f = w₀.app g := by simp [g]
    simp only [Functor.map_comp, weight.weight_comp, w₀_prependPath_map, toList_length,
      FreeSListQuiv.ι_length, asSlist₀_length, List.length_take, FreeSListQuiv.toList_length,
      w₀_swap, FreeMonoid.lift_eval_of, zero_add, f₀, u₀, u₁]
    grind
  -- And now the morphism we built can be reduced thanks to the relations
  apply Quotient.sound
  simpa [g_eq, ← Functor.map_id] using FreeSListQuiv.HomEquiv.prepend _ _ _ (.swap_swap gi₁ gi₂ _)

private theorem map_eq_of_label_eq_braid (k : ℕ) {L : FreeSListQuiv C}
    (hk : L.length = k + 1 + 1) (f : L ⟶ L)
    (i : ℕ) (hi : i < k + 1) (hi' : i + 1 < k + 1)
    (hwf : w₀.app f = (FreeMonoid.of (i + 1) * FreeMonoid.of i) ^ 3) :
    (π C).map f = (π C).map (𝟙 L) := by
  -- setting up some names to make things shorter later on
  let gi₁ : C := (L.toList)[i]'(by grind)
  let gi₂ : C := (L.toList)[i + 1]'(by grind)
  let gi₃ : C := (L.toList)[i + 2]'(by grind)
  let P := FreeSListQuiv.ι C |>.obj <| asSListQuiv <| List.take i L.toList
  let R := FreeSListQuiv.ι C |>.obj <| asSListQuiv <| List.drop (i + 3) L.toList
  -- breaking down `L` as P ++ gi₁::gi₂::gi₃::R
  have :
      L = (P>>).obj (gi₁ ::_ gi₂ ::_ (gi₃ ::_ R)) := by
    apply FreeSListQuiv.injective_toList
    simp [P, R, gi₁, gi₂, gi₃]
  -- Replacing `f` by a morphism with source and target decomposed.
  let g := eqToHom this.symm ≫ f ≫ eqToHom this
  suffices (π C).map g = (π C).map (𝟙 _) by
    simpa [Functor.map_comp, eqToHom_map, Functor.map_id, g, eqToHom_comp_iff,
      comp_eqToHom_iff] using this
  -- building a candidate morphism from `gi₁::gi₂::gi₃::R` to itself with the right label.
  -- The 6 morphisms below simplify via an "hexagon"-type relation.
  let f₀ :=
    (gi₁ ::_ₘ (FreeSListQuiv.swap gi₂ gi₃ R)) ≫
      FreeSListQuiv.swap gi₁ gi₃ (gi₂ ::_ R) ≫
      (gi₃ ::_ₘ FreeSListQuiv.swap gi₁ gi₂ R) ≫
      (FreeSListQuiv.swap gi₃ gi₂ (gi₁ ::_ R)) ≫
      (gi₂ ::_ₘ FreeSListQuiv.swap gi₃ gi₁ R) ≫
      (FreeSListQuiv.swap gi₂ gi₁ (gi₃ ::_ R))
  -- Because of labels, f₀ is equal to `g`.
  have g_eq : g = (P>>).map f₀ := by
    apply eq_of_w₀_app_eq
    simp only [Functor.map_comp, weight.weight_comp, w₀_prependPath_map, toList_length,
      w₀_consPath_map, w₀_swap, FreeMonoid.lift_eval_of, zero_add, f₀]
    have P_length : P.length = i := by grind
    have : w₀.app f = w₀.app g := by simp [g]
    simp only [← this, hwf, P_length, add_comm 1 i]
    grind [pow_three]
  -- Now it just remains to show that f₀ simplifies.
  simp only [g_eq, ← Functor.map_id]
  apply prepend_congr
  have := swap_hexagon gi₁ gi₂ gi₃ ((π C).obj R)
  simp only [π_obj_cons, Functor.map_comp, π_map_cons, eqToHom_refl, Category.comp_id,
    Category.id_comp, Functor.map_id, f₀, swap_π_def]
  simp [←reassoc_of% this, swap_swap_assoc, ← Functor.map_comp_assoc]

theorem map_eq_of_label_eq_braid_inv (k : ℕ) {L : FreeSListQuiv C}
    (hk : L.length = k + 1 + 1) (f : L ⟶ L)
    (i : ℕ) (hi' : i + 1 < k + 1)
    (hwf : w₀.app f = (FreeMonoid.of i * FreeMonoid.of (i + 1)) ^ 3) :
    (π C).map f = (π C).map (𝟙 L) := by
  -- setting up some names to make things shorter later on
  let gi₁ : C := (L.toList)[i]'(by grind)
  let gi₂ : C := (L.toList)[i + 1]'(by grind)
  let gi₃ : C := (L.toList)[i + 2]'(by grind)
  let P := FreeSListQuiv.ι C |>.obj <| asSListQuiv <| List.take i L.toList
  let R := FreeSListQuiv.ι C |>.obj <| asSListQuiv <| List.drop (i + 3) L.toList
  -- breaking down `L` as P ++ gi₁::gi₂::gi₃::R
  have :
      L = (P>>).obj
        (gi₁ ::_ gi₂ ::_ gi₃ ::_  R) := by
    apply FreeSListQuiv.injective_toList
    simp [P, R, gi₁, gi₂, gi₃]
  -- Replacing `f` by a morphism with source and target decomposed.
  let g := eqToHom this.symm ≫ f ≫ eqToHom this
  suffices (π C).map g = (π C).map (𝟙 _) by
    simpa [Functor.map_comp, eqToHom_map, Functor.map_id, g, eqToHom_comp_iff,
      comp_eqToHom_iff] using this
  -- building a candidate morphism from `gi₁::gi₂::gi₃::R` to itself with the right label.
  -- The 6 morphisms below simplify via an "hexagon"-type relation.
  let u₀ := FreeSListQuiv.swap gi₁ gi₂ (gi₃ ::_ R)
  let u₁ := gi₂ ::_ₘ FreeSListQuiv.swap gi₁ gi₃ R
  let u₂ := FreeSListQuiv.swap gi₂ gi₃ (gi₁ ::_ R)
  let u₃ := gi₃ ::_ₘ FreeSListQuiv.swap gi₂ gi₁ R
  let u₄ := FreeSListQuiv.swap gi₃ gi₁ (gi₂ ::_ R)
  let u₅ := gi₁ ::_ₘ FreeSListQuiv.swap gi₃ gi₂ R
  let f₀ := u₀ ≫ u₁ ≫ u₂ ≫ u₃ ≫ u₄ ≫ u₅
  -- Because of labels, f₀ is equal to `g`.
  have g_eq : g = (P>>).map f₀ := by
    apply eq_of_w₀_app_eq
    simp only [Functor.map_comp, weight.weight_comp, w₀_prependPath_map, toList_length, w₀_swap,
      FreeMonoid.lift_eval_of, zero_add, w₀_consPath_map, f₀, u₀, u₁, u₂, u₃, u₄, u₅]
    have P_length : P.length = i := by grind
    have : w₀.app f = w₀.app g := by simp [g]
    simp only [← this, hwf, P_length, add_comm 1 i]
    grind [pow_three]
  -- Now it just remains to show that f₀ simplifies.
  simp only [g_eq, ← Functor.map_id]
  apply prepend_congr
  have := swap_hexagon gi₁ gi₂ gi₃ ((π C).obj R)
  simp only [π_obj_cons, Functor.map_comp, swap_π_def, π_map_cons, Functor.map_id,
    f₀, u₀, u₁, u₂, u₃, u₄, u₅]
  simp [reassoc_of% this, ← Functor.map_comp_assoc, ← Functor.map_comp]

private theorem map_eq_of_label_eq_comm
    (k : ℕ) {L : FreeSListQuiv C}
    (hk : L.length = k + 1 + 1) (f : L ⟶ L) (i : ℕ)
    (j : ℕ) (hj : j < k + 1)
    (hwf : w₀.app f = (FreeMonoid.of i * FreeMonoid.of j) ^ 2)
    (h_lt : i < j) (hij : i + 1 ≠ j) :
    (π C).map f = (π C).map (𝟙 L) := by
  obtain ⟨j, rfl⟩ := Nat.exists_eq_add_of_lt (show i + 1 < j by grind)
  -- Setting up some names to make things shorter later on
  let gi₁ : C := (L.toList)[i]'(by grind)
  let gi₂ : C := (L.toList)[i + 1]'(by grind)
  let gi₃ : C := (L.toList)[i + 1 + j + 1]'(by grind)
  let gi₄ : C := (L.toList)[i + 1 + j + 2]'(by grind)
  let P := FreeSListQuiv.ι C |>.obj <| asSListQuiv <| List.take i L.toList
  let Q := FreeSListQuiv.ι C |>.obj <| asSListQuiv <| List.take j <| List.drop (i + 2) L.toList
  let R := FreeSListQuiv.ι C |>.obj <| asSListQuiv <| List.drop (i + 1 + j + 3) L.toList
  -- breaking down `L` as P ++ [a,b] ++ Q ++ [c, d] ++ R
  have : L = (P>>).obj (gi₁ ::_ gi₂ ::_ ((Q>>).obj <| gi₃ ::_ gi₄ ::_ R)) := by
    apply FreeSListQuiv.injective_toList
    simp only [show i + 1 + j + 1 = i + 2 + j by grind, FreeSListQuiv.appendPath_toList,
      FreeSListQuiv.ι_toList, asSListQuiv_toList, FreeSListQuiv.cons_toList, List.getElem_cons_drop,
      P, gi₁, gi₂, Q, gi₃, gi₄, R]
    simp [show i + 1 + j + 2 = (i + 2 + j) + 1 by grind]
  -- Replacing `f` by a morphism with source and target decomposed.
  let g := eqToHom this.symm ≫ f ≫ eqToHom this
  suffices (π C).map g = (π C).map (𝟙 _) by
    simp only [Functor.map_comp, eqToHom_map, Functor.map_id, g] at this
    rw [eqToHom_comp_iff, comp_eqToHom_iff] at this
    simpa using this
  -- building a candidate morphism with the right label.
  let v₁ :=
    (((P>>).map <| FreeSListQuiv.swap gi₁ gi₂ <|
        (Q>>).obj <| gi₃ ::_ gi₄ ::_ R)) ≫
      ((P>>).map <| gi₂ ::_ₘ gi₁ ::_ₘ ((Q>>).map <| FreeSListQuiv.swap gi₃ gi₄ R)) ≫
      ((P>>).map <| FreeSListQuiv.swap gi₂ gi₁ <|
        (Q>>).obj <| gi₄ ::_ gi₃ ::_ R ) ≫
      ((P>>).map <| gi₁ ::_ₘ gi₂ ::_ₘ (Q>>).map <| FreeSListQuiv.swap gi₄ gi₃ R)
  have g_eq : g = v₁ := by
    apply eq_of_w₀_app_eq
    simp only [weight.weight_comp, w₀_prependPath_map, toList_length, FreeSListQuiv.ι_length,
      asSlist₀_length, List.length_take, FreeSListQuiv.toList_length, w₀_swap,
      FreeMonoid.lift_eval_of, zero_add, w₀_consPath_map, List.length_drop, P, Q, v₁]
    have P_length : P.length = i := by grind
    have : w₀.app f = w₀.app g := by simp [g]
    grind [pow_two]
  -- Now it just remains to show that f₀ simplifies.
  simp only [g_eq, ← Functor.map_id, v₁, ← Functor.map_comp]
  apply prepend_congr
  have := swap_natural gi₁ gi₂ ((π C).map <| (Q>>).map <| FreeSListQuiv.swap gi₃ gi₄ R)
  simp only [π_obj_cons, Functor.map_comp, swap_π_def, eqToHom_refl, Category.comp_id,
    Category.id_comp, π_map_cons, reassoc_of% this, swap_swap_assoc, Functor.map_id]
  simp only [← Functor.map_id, ← Functor.map_comp]
  congr 2
  apply prepend_congr
  simp [swap_π_def, π_obj_cons]

private theorem map_eq_of_label_eq_comm_inv
    (k : ℕ) {L : FreeSListQuiv C}
    (hk : L.length = k + 1 + 1) (f : L ⟶ L) (i : ℕ)
    (hi : i < k + 1) (j : ℕ) (hj : j < k + 1)
    (hwf : w₀.app f = (FreeMonoid.of i * FreeMonoid.of j) ^ 2)
    (hji : j + 1 ≠ i)
    (hij : j < i) :
    (π C).map f = (π C).map (𝟙 L) := by
  obtain ⟨i, rfl⟩ := Nat.exists_eq_add_of_lt (show j + 1 < i by grind)
  -- Setting up some names to make things shorter later on
  let gi₁ : C := (L.toList)[j]'(by grind)
  let gi₂ : C := (L.toList)[j + 1]'(by grind)
  let gi₃ : C := (L.toList)[j + 1 + i + 1]'(by grind)
  let gi₄ : C := (L.toList)[j + 1 + i + 2]'(by grind)
  let P := FreeSListQuiv.ι C |>.obj <| asSListQuiv <| List.take j L.toList
  let Q := FreeSListQuiv.ι C |>.obj <| asSListQuiv <| List.take i <| List.drop (j + 2) L.toList
  let R := FreeSListQuiv.ι C |>.obj <| asSListQuiv <| List.drop (j + 1 + i + 3) L.toList
  -- breaking down `L` as P ++ [a,b] ++ Q ++ [c, d] ++ R
  have :
    L = (P>>).obj (gi₁ ::_ gi₂ ::_ ((Q>>).obj <| gi₃ ::_ gi₄ ::_ R)) := by
    apply FreeSListQuiv.injective_toList
    simp only [show j + 1 + i + 1 = j + 2 + i by grind, FreeSListQuiv.appendPath_toList,
      FreeSListQuiv.ι_toList, asSListQuiv_toList, FreeSListQuiv.cons_toList, List.getElem_cons_drop,
      P, gi₁, gi₂, Q, gi₃, gi₄, R]
    simp [show j + 1 + i + 2 = (j + 2 + i) + 1 by grind]
  -- Replacing `f` by a morphism with source and target decomposed.
  let g := eqToHom this.symm ≫ f ≫ eqToHom this
  suffices (π C).map g = (π C).map (𝟙 _) by
    simp only [Functor.map_comp, eqToHom_map, Functor.map_id, g] at this
    rw [eqToHom_comp_iff, comp_eqToHom_iff] at this
    simpa using this
  -- building a candidate morphism with the right label.
  let v₁ :=
      ((P>>).map <| gi₁ ::_ₘ gi₂ ::_ₘ ((Q>>).map <| FreeSListQuiv.swap gi₃ gi₄ R)) ≫
        ((P>>).map <| FreeSListQuiv.swap gi₁ gi₂ <| (Q>>).obj <| gi₄ ::_ gi₃ ::_ R) ≫
        ((P>>).map <| gi₂ ::_ₘ gi₁ ::_ₘ ((Q>>).map <| FreeSListQuiv.swap gi₄ gi₃ R)) ≫
        ((P>>).map <| FreeSListQuiv.swap gi₂ gi₁ <| (Q>>).obj <| gi₃ ::_ gi₄ ::_ R)
  have g_eq : g = v₁ := by
    apply eq_of_w₀_app_eq
    simp only [weight.weight_comp, w₀_prependPath_map, toList_length, FreeSListQuiv.ι_length,
      asSlist₀_length, List.length_take, FreeSListQuiv.toList_length, w₀_consPath_map,
      List.length_drop, w₀_swap, FreeMonoid.lift_eval_of, zero_add, P, Q, v₁]
    have P_length : P.length = j := by grind
    have : w₀.app f = w₀.app g := by simp [g]
    grind [pow_two]
  -- Now it just remains to show that f₀ simplifies.
  simp only [g_eq, ← Functor.map_id, v₁, ← Functor.map_comp]
  apply prepend_congr
  have := swap_natural gi₁ gi₂ ((π C).map <| (Q>>).map <| FreeSListQuiv.swap gi₃ gi₄ R)
  -- have := swap_hexagon gi₁ gi₂ gi₃ R
  -- 4 nonterminal simps...
  simp only [π_obj_cons, Functor.map_comp, π_map_cons, eqToHom_refl, Category.comp_id,
    Category.id_comp, swap_π_def, ← reassoc_of% this, Functor.map_id]
  have : (π C).map ((Q>>).map
      (FreeSListQuiv.swap gi₃ gi₄ R ≫ FreeSListQuiv.swap gi₄ gi₃ R)) = 𝟙 _ := by
    simp only [← Functor.map_id]
    apply prepend_congr
    simp [swap_π_def, π_obj_cons]
  -- simp only [swap_swap_assoc, ← Functor.map_comp]
  simp only [← Functor.map_comp_assoc, ← Functor.map_comp, this, ← Functor.map_id]
  simp

section EdgeCases

/-! The edge cases of the theorem that two paths with equal formal permutations are
equal in the quotient where the paths are between empty or singleton lists needs to be proved by
hand separately, but are fortunately not too difficult: all these path types are subsingletons! -/

private theorem eq_of_path_of_length_eq_zero {i j : FreeSListQuiv C}
    (f g : i ⟶ j) (hk : i.length = 0) : f = g := by
  obtain h : j.length = 0 := (FreeSListQuiv.length_eq_of_hom f ▸ hk)
  obtain rfl : i = []_ := FreeSListQuiv.length_eq_zero_iff.mp hk
  obtain rfl : j = []_ := FreeSListQuiv.length_eq_zero_iff.mp h
  obtain rfl : f = 𝟙 _ := FreeSListQuiv.eq_id_of_hom_nil f
  obtain rfl : g = 𝟙 _ := FreeSListQuiv.eq_id_of_hom_nil g
  rfl

private theorem eq_of_path_of_length_eq_one {i j : FreeSListQuiv C}
    (f g : i ⟶ j) (hk : i.length = 1) : f = g := by
  obtain h : j.length = 1 := (FreeSListQuiv.length_eq_of_hom f ▸ hk)
  obtain ⟨u, rfl⟩ := FreeSListQuiv.length_eq_one_iff.mp hk
  obtain ⟨u', rfl⟩ := FreeSListQuiv.length_eq_one_iff.mp h
  cases f using FreeSListQuiv.cases_hom_singleton
  cases g using FreeSListQuiv.cases_hom_singleton
  rfl

end EdgeCases

/-- The weight w₂ is faithful: two formal compositions in
`FreeSListQuiv C` with same labels are equal as morphisms of
symmetric lists. This is theorem 2.3 in the paper.
-/
theorem π_map_eq_of_w₂_eq {i j : FreeSListQuiv C} (f g : i ⟶ j)
    (h : w₂.app f = w₂.app g) :
    (π C).map f = (π C).map g := by
  generalize hk : i.length = k
  -- The case of length ≤ 1 are handled in previous theorems
  obtain _ | _ | k := k
  · simp [eq_of_path_of_length_eq_zero f g hk]
  · simp [eq_of_path_of_length_eq_one f g hk]
  · /- First, we reduce the equality `h` to an equality in an appropriate
    Coxeter monoid of type Aₙ -/
    replace h := congr(Ainf.groupToMonoid $h)
    rw [← w₂_app_eq'' k f (by grind), ← w₂_app_eq'' k g (by grind)] at h
    have h := injective_AnToAinfMonoid _ h
    simp only [wFin_app_eq'] at h
    have := Quotient.exact h
    clear h
    clear h
    generalize hwf : (w₀Fin k).app f = wf at this
    generalize hwg : (w₀Fin k).app g = wg at this
    /- Then, we begin an induction on `h`, reducing it to all the
    cases for the symmetric transitive closure of the congruence
    generated by the relations in the Coxeter group -/
    induction this generalizing i j with
    | of x y h =>
      -- The case of a "pure relation"
      cases h with | intro i' j' =>
      obtain rfl : i = j := by
        apply eq_of_w₀Fin_eq' k (f := 𝟙 i) (g := g) (by grind)
        simpa using hwg.symm
      obtain rfl : g = 𝟙 _ := by
        apply eq_of_w₀Fin_eq k (by grind)
        simpa
      clear hwg
      simp only [CoxeterMatrix.Aₙ, Matrix.of_apply, pow_ite, pow_one] at hwf
      rcases i' with ⟨i', hi'⟩
      rcases j' with ⟨j', hj'⟩
      replace hwf := congr((valEmb _) $hwf)
      simp only [Fin.ext_iff, apply_ite (f := valEmb (k + 1)), map_mul,
        FreeMonoid.lift_eval_of, map_pow, valEmb_w₀Fin (hn := hk)] at hwf
      split_ifs at hwf with h' h''
      /- Each of the Coxeter relations have been explicitly handled in previous lemmas,
      following the exact same pattern of "guessing" what the morphisms are from
      their label, and showing that the relations are satisfied once the morphism
      is known.-/
      · subst h'
        exact map_eq_of_label_eq_sq k hk i' hi' f hwf
      · clear h'
        rcases h'' with rfl | rfl
        · exact map_eq_of_label_eq_braid k hk f j' hj' hi' hwf
        · exact map_eq_of_label_eq_braid_inv k hk f i' hj' hwf
      · push_neg at h' h''
        obtain ⟨hji, hij⟩ := h''
        by_cases i' < j'
        · exact map_eq_of_label_eq_comm k hk f i' j' (by grind) hwf
            (by grind) hij
        · refine map_eq_of_label_eq_comm_inv k hk f i' hi' j' hj' hwf hji
            (by grind)
    | refl x =>
      subst hwf
      obtain rfl : f = g := eq_of_w₀Fin_eq k (by grind) hwg.symm
      exact .refl _
    | @symm x y r hr =>
      symm
      exact hr _ _ hk hwg hwf
    | @trans x y z r₁ r₂ hr₁ hr₂ =>
      /- In the case for transitivity, we have to lift the extra
      words that appear as actual morphisms: this is only possible
      because we reduced to the smaller group `Aₙ`. Otherwise,
      the lables of the extra words could be too big to be represented
      by a morphism in FreeSListQuiv with `i` as source. -/
      obtain ⟨j₀, f' , hf'⟩ := exists_hom_of_weight_eq i k hk y
      obtain rfl : j = j₀ := by
        subst_vars
        exact eq_of_w₀Fin_congen_rel _ hk r₁
      have := hr₁ f f' hk hwf hf'
      grind
    | @mul w y x z r r' hr hr' =>
      /- Same as transitivity: this is straightforward but only once
      the extra words that appear in the inductive hypotheses are
      lifted to morphisms. -/
      obtain ⟨j₀, f₀ , hf₀⟩ := exists_hom_of_weight_eq i k hk w
      obtain ⟨j₁, f₁ , hf₁⟩ := exists_hom_of_weight_eq j₀ k
        (FreeSListQuiv.length_eq_of_hom f₀ ▸ hk) x
      obtain rfl : j = j₁ :=
        eq_of_w₀Fin_eq' (f := f) (g := f₀ ≫ f₁) k hk (by grind)
      obtain ⟨k₀, g₀ , hg₀⟩ := exists_hom_of_weight_eq i k hk y
      obtain ⟨k₁, g₁ , hg₁⟩ :=
        exists_hom_of_weight_eq k₀ k (FreeSListQuiv.length_eq_of_hom g₀ ▸ hk) z
      obtain rfl : j = k₁ :=
        eq_of_w₀Fin_eq' (f := g) (g := g₀ ≫ g₁) k hk (by grind)
      obtain rfl : j₀ = k₀ := by
        subst_vars
        exact eq_of_w₀Fin_congen_rel k hk r
      have := hr f₀ g₀ hk hf₀ hg₀
      have := hr' f₁ g₁ (FreeSListQuiv.length_eq_of_hom f₀ ▸ hk) hf₁ hg₁
      obtain rfl : f = f₀ ≫ f₁ := eq_of_w₀Fin_eq k hk (by grind)
      obtain rfl : g = g₀ ≫ g₁ := eq_of_w₀Fin_eq k hk (by grind)
      grind

public section toAinf

@[grind inj]
theorem injective_toAinf_app {x y : SList C} : Function.Injective
    (@(toAinf (C := C)).app (x := x) (y := y)) := by
  intro f g h
  cases f with |_ f
  cases g with |_ g
  exact π_map_eq_of_w₂_eq _ _ (by simpa using h)

theorem hom_eq_iff_toAinf_eq {x y : SList C} (f g : x ⟶ y) :
    f = g ↔ toAinf.app f = toAinf.app g := by
  grind

end toAinf

public section toPerm

@[grind inj]
theorem injective_toPerm_app {x y : SList C} : Function.Injective
    (@(toPerm (C := C)).app (x := x) (y := y)) := by
  intro f g h
  cases f with |_ f
  cases g with |_ g
  simp only [toPerm, weight.postComp_app] at h
  exact injective_toAinf_app <| injective_AinfToPerm h

theorem hom_eq_iff_toPerm_eq {x y : SList C} (f g : x ⟶ y) :
    f = g ↔ toPerm.app f = toPerm.app g :=
  ⟨fun h => by rw [h], fun h => by rw [injective_toPerm_app h]⟩

end toPerm

public section toEquiv

@[simps! -isSimp]
public def toEquiv {x y : SList C} (f : x ⟶ y) :
    Fin y.length ≃ Fin x.length where
  toFun j := ⟨toPerm.app f j, toPerm_app_lt_of_lt _ _ j.prop⟩
  invFun j := ⟨(toPerm.app f).symm j, by simpa using toPerm_app_lt_of_lt (inv f) _ j.prop⟩
  left_inv j := by simp
  right_inv j := by simp

@[simp, grind =]
lemma toEquiv_comp {x y z : SList C} (f : x ⟶ y) (g : y ⟶ z) :
    toEquiv (f ≫ g) = (toEquiv g).trans (toEquiv f) := by
  ext
  simp [toEquiv]

lemma toEquiv_comp_apply {x y z : SList C} (f : x ⟶ y) (g : y ⟶ z) (i : Fin z.length) :
    toEquiv (f ≫ g) i = (toEquiv f ((toEquiv g) i)) := by
  simp [toEquiv]

@[simp, grind =]
lemma toEquiv_id (x : SList C) :
    toEquiv (𝟙 x) = Equiv.refl _ := by
  ext
  simp [toEquiv]

@[simp, grind =]
lemma toEquiv_eqToHom {x y : SList C} (h : x = y) :
    toEquiv (eqToHom h) = finCongr (by rw [h]) := by
  ext
  simp [toEquiv]

@[grind _=_]
lemma toEquiv_symm {x y : SList C} (f : x ⟶ y) :
    (toEquiv f).symm = toEquiv (inv f) := by
  ext
  simp [toEquiv]

@[simp, grind =]
lemma toEquiv_hom_inv_apply {x y : SList C} (f : x ≅ y) (t : Fin x.length) :
    (toEquiv f.hom) (toEquiv (f.inv) t) = t := by
  simp [toEquiv]

@[simp, grind =]
lemma toEquiv_inv_hom_apply {x y : SList C} (f : x ≅ y) (t : Fin y.length) :
    (toEquiv f.inv) (toEquiv f.hom t) = t := by
  simp [toEquiv]

theorem hom_eq_iff_toEquiv_eq {x y : SList C} (f g : x ⟶ y) :
    f = g ↔ (toEquiv f) = (toEquiv g) where
  mp h := by rw [h]
  mpr h := by
    rw [hom_eq_iff_toPerm_eq]
    ext k
    by_cases! hl : k < y.length
    · exact congr($h ⟨k, hl⟩)
    · rw [toPerm_app_eq_of_lt _ _ hl, toPerm_app_eq_of_lt _ _ ((length_eq_of_hom f) ▸ hl)]

theorem getElem_toList_toEquiv {x y : SList C} (f : x ⟶ y) (i : Fin y.length) :
     y.toList[i] = x.toList[(toEquiv f) i] := by
  cases f with | @h x y f =>
  simp only [Fin.getElem_fin, toEquiv_apply_val, π_obj_toList, toPerm,
    weight.postComp_app, toAinf_π]
  exact getElem_toList_eq_perm_apply f _ _

set_option backward.isDefEq.respectTransparency false in
/-- An auxiliary lemma doing the heavy lifting (no pun intended) for
`exists_lift_equiv`. This is essentially a variation on `exists_hom_of_weight_eq`. -/
private lemma exists_lift_perm {x : SList C} (φ : Equiv.Perm (Fin x.length)) :
    ∃ (y : SList C) (f : x ⟶ y),
      toEquiv f = (finCongr (length_eq_of_hom f).symm).trans φ := by
  -- essentially exists_hom_of_weight_eq
  cases x with | h x =>
  generalize h : x.length = k
  obtain _ | _ | k := k
  · obtain rfl : x = []_ := FreeSListQuiv.length_eq_zero_iff.mp h
    obtain rfl : φ = 1 := by grind
    use []~, 𝟙 _
    simp [nil_def]
  · obtain ⟨u, rfl⟩ := FreeSListQuiv.length_eq_one_iff.mp h
    obtain rfl : φ = 1 := by grind
    use u ::~ []~, 𝟙 _
    simp [nil_def, π_obj_cons]
  · -- This is essentially a result we already have, though we have
    -- some book-keeping to do to reduce it to this case, as
    -- we need to correct the types through some equivalences.
    have := exists_hom_of_weight_eq (C := C) x k h
    let u := hom1MulEquiv (k + 1)
    let v := (CoxeterMatrix.Aₙ (k + 1)).monoidToGroupMulEquiv
    let w := v.trans u
    have e₀ : ((π C).obj x).length = k + 1 + 1 := by grind
    let ψ : Equiv.Perm (Fin (k + 1 + 1)) := Equiv.permCongrHom (finCongr e₀) φ
    let k₀ := w.symm ψ
    obtain ⟨a, ha⟩ := PresentedMonoid.surjective_mk k₀
    obtain ⟨y₀, f₀, hf₀⟩ := this a
    use (π C).obj y₀, (π C).map f₀
    ext i
    simp only [toEquiv, toPerm, weight.postComp_app, toAinf_π, Equiv.coe_fn_mk, Equiv.trans_apply,
      finCongr_apply]
    have app_eq'' := congr(Ainf.monoidToGroup $(w₂_app_eq'' (C := C) k f₀ (by grind)))
    have := congr(PresentedMonoid.mk (CoxeterMatrix.Aₙ _).monoidRelations $hf₀)
    rw [← wFin_app_eq'] at this
    rw [CoxeterMatrix.monoidToGroup_groupToMonoid] at app_eq''
    rw [← app_eq'', this]
    simp only [AnToAinfMonoid, ha, MulEquiv.symm_trans_apply, Equiv.permCongrHom_coe,
      CoxeterMatrix.monoidToGroupMulEquiv_symm_apply, MonoidHom.coe_comp, Function.comp_apply,
      CoxeterMatrix.monoidToGroup_groupToMonoid, k₀, v, u, ψ, w]
    have := FreeSListQuiv.length_eq_of_hom f₀
    have := Aₙ_to_perm_apply_eq (n := k + 1) (i := i.cast (by grind))
      ((hom1MulEquiv (k + 1)).symm ((finCongr e₀).permCongr φ))
    simp only [Fin.val_cast] at this
    rw [← this]
    simp [hom1MulEquiv]

public theorem exists_lift_equiv {x y : SList C} (φ : Fin y.length ≃ Fin x.length)
    (hφ : ∀ i : Fin y.length, y.toList[i] = x.toList[φ i]) :
    ∃ f : x ⟶ y, toEquiv f = φ := by
  have : y.length = x.length := by rw [← Fin.equiv_iff_eq]; exact ⟨φ⟩
  obtain ⟨z, f₀, hf₀⟩ := exists_lift_perm <|
    (finCongr
      (show x.length = y.length by rw [← Fin.equiv_iff_eq]; exact ⟨φ.symm⟩)).trans φ
  have e₀ : y = z := by
    apply injective_toList
    apply List.ext_getElem
    · grind
    · intro i hiy hiz
      change i < y.length at hiy
      change i < z.length at hiz
      change y.toList[(⟨i, hiy⟩ : Fin _)] = z.toList[(⟨i, hiz⟩ : Fin _)]
      have e₀ := getElem_toList_toEquiv f₀ ⟨i, hiz⟩
      have e₁ := hφ ⟨i, hiy⟩
      rw [e₀, e₁]
      exact List.getElem_of_eq' (by simp [hf₀]) (by simp)
  use f₀ ≫ eqToHom e₀.symm
  ext x
  simp [hf₀]

/-- Lift an equivalence `(Fin y.length ≃ Fin x.length)` to
a morphism in SList. -/
public noncomputable def liftEquiv {x y : SList C} (φ : Fin y.length ≃ Fin x.length)
    (hφ : ∀ i : Fin y.length, y.toList[i] = x.toList[φ i]) :
    x ⟶ y :=
  (exists_lift_equiv φ hφ).choose

@[simp, grind =]
public lemma toEquiv_liftEquiv {x y : SList C} (φ : Fin y.length ≃ Fin x.length)
    {hφ : ∀ i : Fin y.length, y.toList[i] = x.toList[φ i]} :
    toEquiv (liftEquiv φ hφ) = φ :=
  exists_lift_equiv φ hφ |>.choose_spec

/-- Lift an equivalence `(Fin y.length ≃ Fin x.length)` to
an isomorphism in SList. -/
@[simps]
public noncomputable def liftEquivIso {x y : SList C} (φ : Fin y.length ≃ Fin x.length)
    (hφ : ∀ i : Fin y.length, y.toList[i] = x.toList[φ i]) :
    x ≅ y where
  hom := liftEquiv φ hφ
  inv := liftEquiv φ.symm (by grind)
  hom_inv_id := by rw [hom_eq_iff_toEquiv_eq]; grind
  inv_hom_id := by rw [hom_eq_iff_toEquiv_eq]; grind

end toEquiv

end Relations

end CategoryTheory.SList
